version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://database:27017/quadb
    restart: always

  database:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
